


go mod tidy

GOTOOLCHAIN=auto GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
go build -v -o ./V2bX-linux-amd64 \
  -tags "xray with_reality_server with_quic with_grpc with_utls with_wireguard with_acme" \
  -trimpath -ldflags "-s -w -buildid=" \
  .